version: '3.8'

services:
  # TME Portal Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://tme_user:${POSTGRES_PASSWORD}@postgres:5432/tme_portal
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://192.168.97.149
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - tme_network
    volumes:
      - app_uploads:/app/public/uploads

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5434:5432"  # Enable local development access on port 5434
    environment:
      - POSTGRES_DB=tme_portal
      - POSTGRES_USER=tme_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8
      - TZ=UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    restart: unless-stopped
    networks:
      - tme_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tme_user -d tme_portal"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres 
      -c log_statement=all
      -c log_destination=stderr
      -c log_min_duration_statement=1000
      -c shared_preload_libraries=pg_stat_statements
      -c timezone=UTC

  # Redis Cache for Sessions
  redis:
    image: redis:7-alpine
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - tme_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Database backup service
  backup:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=tme_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=tme_portal
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./scripts/backup.sh:/backup.sh
    networks:
      - tme_network
    entrypoint: ["sh", "/backup.sh"]
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    external: true
    name: tmeportalv52_postgres_data
  redis_data:
    external: true
    name: tmeportalv52_redis_data
  app_uploads:
    driver: local

networks:
  tme_network:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.30.0.0/16